### ISSUE TITLE
Update all strings localization

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#176]
<img width="734" alt="Screen Shot 2021-08-24 at 4 46 32 PM" src="https://user-images.githubusercontent.com/3868028/130688039-469cf25f-27ab-4974-8b4c-15fb6d2a1301.png">

**Comment by olatechpro** [comment]
Hi @stevejburge, the Auto replacing for example, 'organize-series' to 'orgSeries'(which is the plugin file slug) is difficult as it's breaking the plugin due to the fact the plugin path 'organize-series' is referenced in some parts of the plugin and decided to take another approach.

That aside, something came to my mind that i feel may need clarification.

- The plugin folder is 'organize-series'
- The plugin primary file is 'orgSeries.php'

So, that brings confusion on what the plugin slug is.

Is it the directory folder or the primary file ?

**Comment by stevejburge** [comment]
It’s the URL on WordPress.org, I believe

**Comment by olatechpro** [comment]
All right, that make sense
