### ISSUE TITLE
Add new %post_title_list_short% shortcode

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#241]
> The series post list box only displays the full post title. It doesn’t use the information from the “Post title in widget”.
> 
> I understand that the series post list box is NOT the widget, but it seems silly that one place would use this alternate title and the other would not.
> 
> It would be super-simple to create another token like %post_title_list_short% for use in the series post list template.
> 
> Can this please be added for the next release?

https://wordpress.org/support/topic/series-post-list-box-titles/

**Comment by PeterBeckley** [comment]
I had done a pull request on GIT years ago for this, and it was rejected because the original plug-in author said the whole thing was going through a major rewrite. I never revisited this, but have had it working on my own copy for a long time. I wanted to bring my version up-to-date since you guys took over, but of course lost this functionality. I just updated the orgSeries-utility file to add that token and it's working. So either most of my code was used and the token was omitted back then or the functionality has mostly been there and just needed the token_replace updated:

`if( stristr($replace, '%post_title_list_short%') )
	$replace = str_replace('%post_title_list_short%', get_series_posts($id, TRUE), $replace);`

**Comment by stevejburge** [comment]
Awesome, thanks @PeterBeckley 

I'll schedule this for 2.6.3, the next release
