### ISSUE TITLE
wp_serieslist_display() Not Working

### ISSUE THREAD

**Issue by rami4625** [publishpress/publishpress-series#287]
I’m using `<?php wp_serieslist_display(); ?>` code to show the Table of Contents and every thing was fine until i tried to change the number of Series Per Page in Plugin Options then wp_serieslist_display() return nothing!

I tried to reset the number like it was but nothing change,
Also i tried to restore plugins backup and also nothing change!

Link of issue:
https://elakademiapost.com/series-toc/

**Comment by stevejburge** [comment]
Screenshot:
<img width="887" alt="Screen Shot 2021-11-03 at 10 56 29 AM" src="https://user-images.githubusercontent.com/3868028/140084937-8c08919b-b478-4045-9f53-a67f6094e41d.png">

**Comment by rami4625** [comment]
في الأربعاء، ٣ نوفمبر ٢٠٢١ ٤:٥٨ م Steve Burge ***@***.***>
كتب:

**Comment by rami4625** [comment]
It's not appear as you see

في الأربعاء، ٣ نوفمبر ٢٠٢١ ٥:١٩ م Rami Alkhateeb ***@***.***> كتب:

**Comment by rami4625** [comment]
Hi,
Is that a bug or what?

في الأربعاء، ٣ نوفمبر ٢٠٢١ ٥:٢٥ م Rami Alkhateeb ***@***.***> كتب:

**Comment by rami4625** [comment]
Great!
We are waiting the new release,

Thank you for your efforts.

**Comment by olatechpro** [comment]
@stevejburge @rami4625 this doesn't seems to be issue related to last or previous release while tracing back the code.

Can you confirm the version where this was working as i rolled back to some earlier version and still seeing the error.

The reason i need to get version where this is working is to make things easy as right now, the template that output the function is completely missing and finding the version where it was working will make it a case of just copying and pasting it back rather than developing this feature from start again.

**Comment by olatechpro** [comment]
@stevejburge . After spending my whole day trying to get this issue(the fact that rolling back is not fixing it make it more difficult to debug), finally had a breakthrough even though it's suppose to be a very simple issue.

The problem started here 'https://github.com/publishpress/publishpress-series/issues/260' when you said you didn't understand what the field is been used for and we later took the conversation to slack where we concluded it should be removed.

On reason why rolling back to prior version is not fixing the issue, it's because after updating series option, the field data is completely removed and rolling back won't fix that.

So, i'm about to push the update now but still want you to revisit the linked issue so we can conclude on if we should bring back the field description as without it, users won't be aware of where it's been used.

**Comment by stevejburge** [comment]
Thanks @olatechpro 

So this is something that can only be used via a PHP snippet?

**Comment by olatechpro** [comment]
Yes, only used via the `<?php wp_serieslist_display(); ?>` function @stevejburge

**Comment by olatechpro** [comment]
Here's the original description 
![des](https://user-images.githubusercontent.com/46832636/135278695-93badfce-c344-45e3-8368-0de2139c8c55.jpg)

**Comment by stevejburge** [comment]
OK, thanks. Maybe we can add it in an "Groups" area for now?

I think this circles back to this problem that the Groups feature was never properly built:
https://github.com/publishpress/publishpress-series/issues/202

Here's the documentation: https://publishpress.com/knowledge-base/table-of-contents/

**Comment by olatechpro** [comment]
Okay, I think this made me understand the linked issue as well now.

So, what's the next action on this ? @stevejburge

**Comment by olatechpro** [comment]
I didn't understand what the group area mean or referring to @stevejburge

**Comment by stevejburge** [comment]
OK, this was a mistake on my part, and it seems like the /series-toc/ URL is only active under some conditions. For example, it doesn't work on localhost, unless you enable permalinks the correct way

I did finally get it work. 

My settings:

<img width="852" alt="Screen Shot 2021-11-11 at 12 34 56 PM" src="https://user-images.githubusercontent.com/3868028/141343259-eff3c057-f26c-448e-93d7-781eda8d291a.png">

My result:

<img width="758" alt="Screen Shot 2021-11-11 at 12 33 33 PM" src="https://user-images.githubusercontent.com/3868028/141343141-0763fc69-9f2f-42ec-bccd-ce0fa535f5cb.png">

@olatechpro Can we add this back here?

Title: Series Table of Contents
Description: This display is used by the "Series Table of Contents". To find the URL for this display, go the "Display" tab and then "Series Table of Contents URL".

![Screen Shot 2021-11-11 at 12 35 54 PM](https://user-images.githubusercontent.com/3868028/141343392-ea4d98d0-ca5d-4c57-b815-b6c81830bfb1.png)

**Comment by rami4625** [comment]
@olatechpro you can find the option in version: 2.5.0

**Comment by olatechpro** [comment]
> @olatechpro you can find the option in version: 2.5.0

Thanks, the fix will be available in next release which will probably come through on Monday or Tuesday but if you need a test copy before then, we can share.
