### ISSUE TITLE
Improved design for Series overview page

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#309]
Our default Series overview page is not very basic. We could offer more layout options:

<img width="1254" alt="Screen Shot 2021-11-29 at 12 14 57 PM" src="https://user-images.githubusercontent.com/3868028/143912953-3e46f3b0-bec8-41fb-a6e2-73b7b6983e1f.png">

One user requested an overview page like this: https://wvdn.com/archives/

It would a create a thumbnail view for each icon:
<img width="780" alt="Screen Shot 2021-11-24 at 1 07 23 PM" src="https://user-images.githubusercontent.com/3868028/143292095-db790b55-9cc7-4874-bc49-72b51126f58e.png">

**Comment by stevejburge** [comment]
Here's a similar design that one customer has set up:
<img width="769" alt="Screen Shot 2021-12-02 at 1 55 15 PM" src="https://user-images.githubusercontent.com/3868028/144485343-177b3fc6-7476-42b3-8249-bad925118eb6.png">

**Comment by htmgarcia** [comment]
@stevejburge the series overview page is a taxonomy page, inherited from the core. What we want to achieve here is a custom template for series taxonomy. These templates loads through a theme. I'll check for a way to do it through the plugin.

**Comment by htmgarcia** [comment]
@stevejburge I figured out a way to override the theme taxonomy template, however this is not suitable due means we'd override the whole taxonomy page for the theme in use (including theme header and footer) and potentially break the site due each theme is developed in unique ways.

I have a suggestion. In order to be able to showcase different designs for an overview page, we can create a custom post type (only to use in the front) as a new optional overview page following the PublishPress Authors box approach which content is attached to a post without messing with the theme. 

Please note: this approach will remove "series" slug from the URL due will be a post.

![series-cpt](https://user-images.githubusercontent.com/4999794/144508422-9daf141a-03a5-48ba-96bd-2fe7e2a369cf.jpg)

![Screen Shot 2021-12-02 at 15 52 14](https://user-images.githubusercontent.com/4999794/144509052-3e125eb1-aa7a-435c-aa47-9c70b739c8d3.png)

cc @olatechpro

**Comment by stevejburge** [comment]
That's a great idea, thanks @htmgarcia 

I'll also work on improving the documentation to explain how this feature works now.

**Comment by htmgarcia** [comment]
@olatechpro since you are more familiar with the plugin, I appreciate any feedback on this proposal.

> @stevejburge I figured out a way to override the theme taxonomy template, however this is not suitable due means we'd override the whole taxonomy page for the theme in use (including theme header and footer) and potentially break the site due each theme is developed in unique ways.
> 
> I have a suggestion. In order to be able to showcase different designs for an overview page, we can create a custom post type (only to use in the front) as a new optional overview page following the PublishPress Authors box approach which content is attached to a post without messing with the theme. 
> 
> Please note: this approach will remove "series" slug from the URL due will be a post.
> 
> ![series-cpt](https://user-images.githubusercontent.com/4999794/144508422-9daf141a-03a5-48ba-96bd-2fe7e2a369cf.jpg)
> 
> ![Screen Shot 2021-12-02 at 15 52 14](https://user-images.githubusercontent.com/4999794/144509052-3e125eb1-aa7a-435c-aa47-9c70b739c8d3.png)

> Update: ugh... the CPT for each series should be generated automatically due would work as a kind of template.

**Comment by olatechpro** [comment]
@htmgarcia i also have the need to overwrite taxonomy page for 'series group' i'm current working on and opt for 'template_include' that allow me to render taxonomy pages from plugin.

You're right on the fact the whole page been a blank template and need to include header, sidebar, footer etc which is the native need of archive.

To me, considering the advantage over disadvantages, i still feel like we can go with this since series is our creation and unless user create a custom archive page for a taxonomy, large percentage of sites are always rendered via theme archive.php.

Now, for the percentage of themes that may have an extensively customised archive page with different layout and needs outside native archive page with header, loop, sidebar and footer, we can make it possible for them to over-ride the plugin template inside their theme/child-theme. That way, if any theme needs is custom, they can always copy the template to their child theme to customise or simply create the series template since we'll always check if the series template exists in their theme before using our custom template.

In addition, we can have a checkbox that allow user check if they want to use the custom template or not.

That way, we're considering everyone and giving them will/option to use their template or copy and customise our own inside their child theme or opt out if it's not working for them..

Making our template over-rideable is already an advance feature for custom theme needs even though our template is based on native theme archive page needs. Even if we go with cpt option, it'll also have it own disadvantages and theme it won't work with, for example, we're currently having main series hooking to the_content #306 due to theme that include pages as header. Thinking about it now, the best option to solve such issue is rendering the series on our plugin template with option for user to customise/over-ride it in their theme.

Series is 100% our creation. So, until user started using series, it shows the series archive or custom design for it doesn't exist for the theme.

So, no-matter the approach we take, there'll always be compatibility issues with some themes since application is frontend and choosing the most appropriate option will be better so far we make it flexible for changes.

On CPT, some may feel duplicate cpt of their series page will/may hurt their SEO.

This is just my opinion based on the same issue i'm working on and @stevejburge can have comments and further discussion on what's the best thing to do.

**Comment by stevejburge** [comment]
@olatechpro @htmgarcia Thanks for the detailed feedback.

If we need to do this for Groups, we may as well do this for the Series Overview also?

**Comment by htmgarcia** [comment]
> On CPT, some may feel duplicate cpt of their series page will/may hurt their SEO.

@olatechpro good point. That is another a very important concern to consider.

Thanks for the detailed feedback! I was using "template_include" approach in my first try. My worry is the series page won't fit the design of other themes due the HTML of the custom template we implement. As example, title design maynot be the same if a theme implement a class to style this element. It may lead to design inconsistency, however I see a positive point on allowing users to create their own template override to fix any design inconsistency.

@stevejburge besides the approach we take, there will be incompatibilities for some themes. After reading Ola's feedback, overriding the taxonomy template seems the safest choice because is an option that WordPress cores provides.

**Comment by htmgarcia** [comment]
@stevejburge this scenario reminds me PP Authors custom overrides for some popular themes to support the multiple authors in posts that Anderson implemented.
