### ISSUE TITLE
Visual bug with the "Series Taxonomy" choice

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#312]
If you update the taxonomy, it still shows the old taxonomy.

The "Series Taxonomy Slug" box won't update to show the current taxonomy:

<img width="842" alt="Screen Shot 2021-11-26 at 4 07 10 PM" src="https://user-images.githubusercontent.com/3868028/143649813-f03c509a-e045-43e3-9dc2-1eecac65caf2.png">

**Comment by olatechpro** [comment]
I think the problem here is with the label 'Series Taxonomy slug'.

It should either be 'series taxonomy name' or 'series taxonomy' or 'series taxonomy registration key'.

It's an easy process to change taxonomy slug compare to when changing taxonomy registration name itself and it basically refer to the taxonomy base which i believe it already exist in settings as shown below:

<img width="1920" alt="Screenshot 2021-11-29 at 6 31 32 PM" src="https://user-images.githubusercontent.com/46832636/143915480-273d3b30-b466-4b00-ab86-e18cc1192131.png">

**Comment by stevejburge** [comment]
Yes, good plan, thanks @olatechpro
