### ISSUE TITLE
Improve design of "Publish Series"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#393]
Related to https://github.com/publishpress/publishpress-series/issues/392

Can we improve the design of this screen to look more the main "Post screen"

- Show the scheduled date if the series is scheduled
- Make it clearer what "Publish", "Unpublish" and "Ignore" mean. Should it be "Publish all posts in this Series" for example?
- Add a "View" link to the frontend

![Screen Shot 2022-02-03 at 1 21 53 PM](https://user-images.githubusercontent.com/3868028/152404784-37fef750-04bd-4aef-903c-317dd8b0ec52.png)

**Comment by olatechpro** [comment]
@stevejburge the Publish series literally called all series posts depending on status (published or not) and doesn't have record or take any action for scheduled series. So, the "...the scheduled date if the series is scheduled" can not work as it doesn't schedule post but instead publish or un-publish series posts by changing the series posts status.

In summary, the feature only do one thing which is to update series posts status and doesn't manage individual series data.

**Comment by olatechpro** [comment]
I've done the following:
- Updated 'Publish' to 'Publish all posts in this Series',
- Updated 'Unpublished all posts in this Series'
- On how ignore works, when you click 'unpublish', the last action will be saved and as a result, the unpublish will become text instead of link as it is and when you click 'publish', the publish link will be removed and become text also. So, it basically track the last click action and when you click 'ignored', it remove tracking status and both publish and unpublish become link again.

So, what should i update the 'Ignore' button text to having updated the publish and unpublish ? @stevejburge

**Comment by olatechpro** [comment]
@stevejburge , on another note, if we store scheduled status if date is future date, this will leave room for another issue like status not changing even when these posts are published and also inaccurate status since practically, the publish screen depends on live posts which shows new posts are not schedule while we leave impression of all posts in the series been scheduled.

In short, scheduled status is post related and not series related. So, it's inaccurate to define such status in series

**Comment by stevejburge** [comment]
@olatechpro Thanks for this. Do you mind if we close this for now and I come back to them once I'm able to test the changes in a Beta version?

**Comment by olatechpro** [comment]
ok

**Comment by stevejburge** [comment]
@olatechpro I've opened a couple of tickets that may refer back to this one including:
https://github.com/publishpress/publishpress-series/issues/439. 

I wonder if I'm missing something in my test version? I don't see all your changes

**Comment by olatechpro** [comment]
I don’t really understand, thought your last message on this issue was to leave it then ? @stevejburge

**Comment by stevejburge** [comment]
Ah, sorry. My fault. I should have explained it better.

I was unclear on the impact of your changes. But can you make the changes? Then we can discuss with real screens to look at
