### ISSUE TITLE
Scheduled series as shown as "Published"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#439]
I scheduled a series to go live and posts are scheduled:
<img width="340" alt="Screen Shot 2022-03-04 at 12 34 14 PM" src="https://user-images.githubusercontent.com/3868028/156813264-4ae4adc3-5745-49f3-b73d-b17da8946997.png">

However, the "Publish Series" screen doesn't reflect that. It says "Published"
<img width="1186" alt="Screen Shot 2022-03-04 at 12 33 32 PM" src="https://user-images.githubusercontent.com/3868028/156813304-3f32f870-143a-4b13-aaee-c7c40c8d2f84.png">

**Comment by olatechpro** [comment]
@stevejburge , i already tried to explain this issue or how this features work here https://github.com/publishpress/publishpress-series/issues/393#issuecomment-1059380717

When you click Publish, Individual posts status are not managed at terms level when when you click publish as your last action, the button will changed to text as published to signify the action that was last taken and if you click unpublished as last button, the unpublished link will change to text as well to signify the action taken.

i don’t really know how better to explain this, that screen you screenshot is terms screen and not posts and it’ll be too expensive for us to manage all series posts status when it’s possible for some posts to be published, some scheduled, some draft etc.

if you feel it’s confusing, we can always leave it as link to be clickable instead of updating last action and that way, we eliminate the ignore button because the purpose of ignore is to prevent these status update.

**Comment by olatechpro** [comment]
If you click ignore, action will be reset and both publish and unpublish will become clickable again

**Comment by stevejburge** [comment]
@olatechpro Thanks for the details. Let's start here ... if I'm confused, our users will be more confused.

Maybe we need to change the purpose of the screen with additional columns?
https://github.com/publishpress/publishpress-series/issues/436

**Comment by olatechpro** [comment]
Yes, eliminating the ignore button and making the link clickable all time will fix the confusion in addition to the new columns.

**Comment by stevejburge** [comment]
Thanks Ola. Yes, this screen is not much good right now. 

Let's be brave and re-think it.
