### ISSUE TITLE
Scheduled posts marked with no Part

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#452]
I used the Publish Series screen and scheduled 5 posts. They are all marked this way:

<img width="1406" alt="Screen Shot 2022-03-08 at 1 23 59 PM" src="https://user-images.githubusercontent.com/3868028/157301595-eb58a337-1320-4d8d-8fb0-ab5609daab1d.png">

**Comment by olatechpro** [comment]
Closing this in favour of https://github.com/publishpress/publishpress-series/issues/454 , they are same issue.

**Comment by olatechpro** [comment]
**Additional note**, series only apply part to post with published status and not pending or future(scheduled) unless the part is entered by user.

To enable part for scheduled post, we're changing this condition for publish series feature but leaving this note here incase this lead to another problem since the whole series build and code only support publish status and it's hard to guess what the implication of this implementation will be since we inherit the series code.

**Comment by olatechpro** [comment]
So, the update was made by adding part meta for scheduled series and will now read " (currently set as Part 1)' with no total series since total series only count published series and this affect frontend as well as doing otherwise means the frontend will show pending and scheduled series in the total part summary.
