### ISSUE TITLE
%post_title_list_short% Doesn't work

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#523]
> %post_title_list_short% Doesn't work outputs full headers all the same

https://wordpress.org/support/topic/post_title_list_short/
<img width="946" alt="Screen Shot 2022-04-21 at 12 05 43 PM" src="https://user-images.githubusercontent.com/3868028/164503463-232248fa-46d3-4441-a49d-baff84c19f68.png">

**Comment by olatechpro** [comment]
@stevejburge I'm not able recreate this problem. Also:
1. The link you added to the issue description is not related to the issue. So, i wasn't able to check full report 
2. I believe it may be related to https://github.com/publishpress/publishpress-series/issues/473 but it has been released since April.

**Comment by stevejburge** [comment]
This seems to be confirmed: https://wordpress.org/support/topic/post_title-and-post_title_linked-are-both-links/

**Comment by olatechpro** [comment]
New token added: `%post_title_short%` and `%post_title_short_linked%`
