### ISSUE TITLE
Add series order link to series and new post selected series

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#612]
I've seen several situations where two parts can share the same number. For example: https://github.com/publishpress/publishpress-series/issues/611

Should we make this impossible?

**Comment by olatechpro** [comment]
Not sure if any work needed to be done on this unless I didn't understand the issue.

I "**Automatic Numbering"** is disabled, the user can use any numbering they want which including using same part for as many series as they want.

@stevejburge

**Comment by olatechpro** [comment]
That shows we're going back to a problem we fixed by adding that "Automatic Numbering" settings which is inability to make changes easily.

For example, if Part 10 exist and the user want to have new part 10 then change the previous part 10 later.

If we decide to auto increase to next number, that leads to previous problem with auto series and related issue.

After our previous fix, it's not possible to have same part when automatic numbering is enabled but if disabled, user are responsible for the value but if you don't want this, then make a full proposal of how this should be so it can be noted instead of introducing part bugs we were trying to fix by introducing the settings

**Comment by olatechpro** [comment]
That shows we're going back to a problem we fixed by adding that "Automatic Numbering" settings which is inability to make changes easily.

For example, if Part 10 exist and the user want to have new part 10 then change the previous part 10 later.

If we decide to auto increase to next number, that leads to previous problem with auto series and related issue.

After our previous fix, it's not possible to have same part when automatic numbering is enabled but if disabled, user are responsible for the value but if you don't want this, then make a full proposal of how this should be so it can be noted instead of introducing part bugs we were trying to fix by introducing the settings @stevejburge

**Comment by olatechpro** [comment]
@stevejburge This is more complicated than you explain.

How do you think this should happen with error output.

We prevent post submission when creating or updating post with message?


And in bulk edit, how does it work?

**Comment by stevejburge** [comment]
@olatechpro That's a good point. The error output will be tricky.

Maybe we go all-in on links to the "Series Order" screen. I have two examples above. We can add a 3rd:
![Screen Shot 2022-09-14 at 2 34 21 PM](https://user-images.githubusercontent.com/3868028/190235373-603abe59-4458-4550-b726-dc78db733fd4.png)
