### ISSUE TITLE
Move Series Table of Contents to the content body

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#618]
Related to https://github.com/publishpress/publishpress-series/issues/600

Certainly the "Table of Contents" should be moved, perhaps into the content body?

It is a strange choice to have it floating:

![Screen Shot 2022-09-14 at 1 49 22 PM](https://user-images.githubusercontent.com/3868028/190227473-3651068f-169f-42f2-88ff-f8cdaa4f1038.png)

This leads to some bad layouts:

![Screen Shot 2022-09-14 at 1 53 10 PM](https://user-images.githubusercontent.com/3868028/190227519-d6f72682-c578-4026-9ebe-a273748a83c2.png)

**Comment by olatechpro** [comment]
@stevejburge The TOC can't stay beside the date and category where you put the **???** as it's not post content and not all themes has that at the highlighted location and position.

However, I've adjusted the series toc content to be full width and stay with content instead of the sidebar.

In addition, to determine if it stays on top or bottom of the content, the position can be configured in settings as shown below

![setting-1](https://user-images.githubusercontent.com/46832636/192258413-0eab738a-61f9-4d93-aba3-3a89c1be8c80.jpg)


So, with lates update and the suggested testing, here's the result:

![updated-](https://user-images.githubusercontent.com/46832636/192258955-f47cf722-93e9-4ab4-8d7f-54c123454b49.jpg)
