### ISSUE TITLE
Series order issue in 'Series Table of Contents' Widget (by 'series id' in 'ascending' order)

### ISSUE THREAD

**Issue by mtlemissova** [publishpress/publishpress-series#680]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Steps to Reproduce (for bugs)

1. Appearance
2. Widgets
3. Add Block
4. Find 'Series Table of Contents'
5. 'Order by: 'series id' and 'Order: Ascending
6. 'Update' and check the results
Note: Series are not in order (in fact nothing has changed in widget series order)

## Your Environment

* Version used: Version 2.10.0
* Browser Name and version: Chrome/Version 105.0.5195.125
* Operating System and version (desktop or mobile): MacOS Monterey / Version 12.4
* Link to your project:
<img width="1023" alt="Screen Shot 2022-10-11 at 10 12 35 AM" src="https://user-images.githubusercontent.com/107439940/195116865-7cff65c5-35eb-46b1-affa-7b8114e52d31.png">
<img width="1083" alt="Screen Shot 2022-10-11 at 9 59 17 AM" src="https://user-images.githubusercontent.com/107439940/195116868-f0065956-8579-4ef7-8dd2-5dafbb96c7af.png">

**Comment by misfist** [comment]
I have experienced the same issue, using the widget, `wp_serieslist_display()` and native WP `WP_Term_Query`. Regardless of what `orderby` value I use, it is ignored. 

The issue seems originate from:

[`organize-series/orgSeries-manage.php`](https://github.com/publishpress/publishpress-series/blob/development/orgSeries-manage.php#L19)

```
add_filter('terms_clauses', 'pp_series_terms_clauses', 10, 3);
```

I solved this by removing the filter before outputting the list and then re-adding it. But, that won't be possible for someone using the widget.
